### ISSUE TITLE
Unpredictable key press behaviour in search bar

### ISSUE THREAD

**Issue by LukePizon2104** [dbcodeio/public#281]
When pressing o in filter bar of the output , the cell is being hidden
When pressing a in filter bar of the output , new cell is added
How to disable this behaviour?
![Image](https://github.com/user-attachments/assets/2c905738-8aa6-4423-a2a6-6cc81def1f77)

**Comment by mikeburgh** [comment]
That filter bar filters the rows for the value you enter.. so in your screenshot only rows containing qwertyuiooa would be showing. 

If I am not understanding what you mean, can you share a video so I can see it ?

**Comment by mikeburgh** [comment]
Thanks, I see what you mean. I cannot replicate it.. do you have a any keyboard shortcuts for a to add a new cell ? 

I will add some code not let those keyboard entries fire any higher, and we can see if that stops it.

**Comment by mikeburgh** [comment]
A possible fix has been released in 1.6.15, does it solve it ?

**Comment by LukePizon2104** [comment]
Unfortunate the issue still occurs for some reason. Checked the keyboart shortcut preferences but i don't have nothing conflicting with this field

The issue started to appear about 2 weeks ago.

I'll check diffrent wersion on the weekend to pinpoint exact version cousinig the issue

**Comment by mikeburgh** [comment]
Okay confirmed it's coming from the Juypter extension (#284). Now to work around it.

**Comment by LukePizon2104** [comment]
Thanks, much appreciated
