### ISSUE TITLE
Issues with "Save Output: ON" in DBCode Notebook

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#381]
Hi Mike,  

Whenever I try to enable **"Save Output: ON"** in the DBCode notebook, I often encounter the error message: **"Failed to save Notebook Output: Response Timed Out"** (screenshot attached).  

Additionally, I've recently been experiencing delays in opening existing notebooks (with **Save Output: ON**) and sluggish execution of cells. These issues only occur when **Save Output** is enabled in the DBCode notebook.

![Image](https://github.com/user-attachments/assets/c8199934-8df9-4d82-a04f-2b585951cf8b)

**Comment by mikeburgh** [comment]
What sort of size data are you dealing with ? eg number of results being shown, including multiple tabs, and rows per results ? 

If there is a lot, this could be timing out before it all gets serialized. 

Next time if happens (or if you can produce it reliably) open up the developer tools and check the console for errors, I expect there will be something there.

**Comment by mikeburgh** [comment]
Fixed in 1.10.7 it was trying to save the tabs that were still executing.

It looks like those tabs were just hung executing, were they just slow or had they broken and not returning data ? Thats probably the root cause to track down.

**Comment by devpkr1** [comment]
Hey Mike,

The issue still persists—I can't load the saved output.
I've sent you a screen recording via email. Please check.

**Comment by mikeburgh** [comment]
Give it a try now, I have think it should be sorted in 1.13.14.

**Comment by devpkr1** [comment]
Yeah, This is working now
