### ISSUE TITLE
SQL Server: Introspection times out with large number of tables

### ISSUE THREAD

**Issue by mikeburgh** [dbcodeio/public#425]
Following on from #421

With 1000's of tables introspection hangs

**Comment by mikeburgh** [comment]
@ashouppe-pj can you try a few things for me: 

1. Set the db to master or someting in the connection so you can connect.. and then that should let you expand that DB. 

2. Can you run these queries and share the count it returns, basically the total number of tables and columns in the DB.. will give me an idea of what we are looking at so I can try and replicate and come up with a solution.


```sql
select count(*), 'schemas'
from sys.schemas;

select count(*), 'tables'
from sys.tables;

select count(*), 'columns'
from sys.columns;
```

In terms of the introspection, after the first time it is done in the background.. but it needs to run once up front so the extension knows it has all the data..  I guess once I get a handle on the tables count and columns and replicate it on my end, I can see what's possible.

With that many tables, are there any tools you have found that have been able to browse them in an efficient manner ?

**Comment by ashouppe-pj** [comment]
Here are the counts:

Schema - 13
Tables - 26653
Columns - 563915

As for other tools, the ones I have used successfully (SSMS, Azure Data Studio, and a few others) all seem to list the databases, but dont run introspection on the tables, views, sprocs, etc unless I expand that folder specifically. In the case of tables, i usually filter first so it only pulls in data for the tables matching the filter. 

In short, they dont do full introspection for a db of this size, they only do it on demand, per folder of objects, according to a filter that can be set prior to opening the folder.

**Comment by mikeburgh** [comment]
thanks for the info.. so first problem is which query is taking so long and preventing it from returning.. that's going to be challenge 1, then second part will be the performance of turning the raw data from the DB into the schema.. but from the output you shared, it never logs the introspection finished line, which looks like: 

```log
2025-04-10 20:16:09.322 [debug] Connection: introspection of 'code' on 'SQL Server - Dev' starting
2025-04-10 20:16:10.103 [debug] Connection: introspection of 'code' on 'SQL Server - Dev' finished
```

I might need to do a new build with some more logging, but first things first, can you try run these two statements (table and column fetching) don't need the output, just that they work, and rough execution timing: 

```sql
select s.name as schema_name
		,t.object_id as table_id
		,t.name as table_name
		,t.type_desc as table_type
		,ep.value as comment
		,p.rows
		,COALESCE(SUM(p.dataBytes),0) as dataBytes
		,COALESCE(SUM(p.indexBytes),0) as indexBytes
from sys.tables t
join sys.schemas s on (s.schema_id = t.schema_id)
Join (
		select t.object_id
			,p.rows
			,Case When (i.index_id < 2) then SUM(a.used_pages) * 8 * 1024 end AS dataBytes
			,Case When (i.index_id > 1) then SUM(a.used_pages) * 8 * 1024 end AS indexBytes
	from sys.tables t
	INNER JOIN sys.indexes i ON t.OBJECT_ID = i.object_id
	INNER JOIN sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id
	INNER JOIN sys.allocation_units a ON p.partition_id = a.container_id
	Group By t.object_id, t.schema_id, t.name, t.type_desc, p.rows, i.index_id
	) as p on (p.object_id = t.object_id)
left join sys.extended_properties ep on (ep.major_id = t.object_id and ep.name = 'MS_Description' and ep.minor_id = 0)
group by s.name, t.object_id, t.schema_id, t.name, t.type_desc, p.rows, ep.value 
order by table_name;
```

```sql
select s.name as schema_name 
		,ta.name as table_name
		,c.column_id 
		,c.name as column_name
		,t.name
		,case when ic.index_id is not null then CAST(1 as bit) else CAST(0 as bit) end as primaryKey
		,c.is_nullable
		,c.is_rowguidcol
		,c.is_identity
		,c.is_computed
		,definition as computedExpression
		,case when c.precision != 0 then Cast(c.precision as varchar) else 
			case when t.name in ('nvarchar','varchar','varbinary') and c.max_length = -1 then 'max' else 
				case when t.name in ('nvarchar','nchar') then CAST(c.max_length / 2 as varchar) else CAST(c.max_length as varchar) end
			end 
		end as length
		,c.scale
		,case when c.is_identity = 1 then 'identity' else object_definition(c.default_object_id) end AS [default]
		,ep.value as comment
from sys.columns as c
join sys.tables as ta on (c.object_id  = ta.object_id)
join sys.schemas s on (s.schema_id = ta.schema_id)
INNER join sys.types t on (c.system_type_id = t.system_type_id AND c.user_type_id = t.user_type_id)
LEFT JOIN sys.computed_columns as cc on (c.object_id = cc.object_id and c.column_id = cc.column_id)
left join sys.indexes as i on (i.object_id = c.object_id and is_primary_key = 1)
left join sys.index_columns as ic on (i.index_id = ic.index_id and c.object_id = ic.object_id and c.column_id = ic.column_id )
left join sys.extended_properties ep on (ep.major_id = c.object_id and ep.name = 'MS_Description' and ep.minor_id = c.column_id);

```

**Comment by ashouppe-pj** [comment]
Both queries work, though the first one did drop a warning stating "Warning: Null value is eliminated by an aggregate or other SET operation."

**First Query:**

(26654 rows affected)
Total execution time: 00:00:31.215

**Second Query:**

(537409 rows affected)
Total execution time: 00:00:21.495

**Comment by mikeburgh** [comment]
Okay that's a good sign, means the data is coming back, just need to figure out where the issue lies in transforming it.

Can you update to 1.11.6 which was just released, and then try and connect again with debug turned on.. should show something like this: 

```
2025-04-11 20:00:39.645 [debug] Connection: introspection of 'code' on 'SQL Server - Dev' starting
2025-04-11 20:00:39.646 [debug] MSSQL: executing query on 'SQL Server - Dev'
2025-04-11 20:00:39.844 [debug] MSSQL: processing query results on 'SQL Server - Dev', recordsets: 19
2025-04-11 20:00:39.846 [debug] Connection: introspection of 'code' on 'SQL Server - Dev' finished
2025-04-11 20:00:39.904 [debug] Connection: mapping introspection of 'code' on 'SQL Server - Dev' to schema
2025-04-11 20:00:39.904 [debug] Connection: injecting datatypes for 'code' on 'SQL Server - Dev'
2025-04-11 20:00:39.904 [debug] Connection: generating relationships in 'code' on 'SQL Server - Dev'
```
and share the output you get? 

I added some more detail to the steps, so we can get a handle on where it stops.

**Comment by mikeburgh** [comment]
I have replicated it on my end.. It's a call stack problem.. I refactored it to not be recursive, but it's still blowing the stack building a processing queue… I should be able to solve it, just need to do some more work…

**Comment by mikeburgh** [comment]
I might have taken it too far, but I have 87k tables loading.. still slow, but they load.. was more interested to test other performance like autocomplete etc.. and it's all decent, just need to get more loading performance now

<img width="414" alt="Image" src="https://github.com/user-attachments/assets/f0d89329-9141-46d9-8476-9f1c740ffe86" />

Currently the performance improvement is about 40%

```
Very large dataset: 20000 tables with 20 columns each (400000 total items)
--------------------------------------------------------
Original (recursive): 96508.13ms
Optimized (non-recursive): 98283.28ms
Ultra-Optimized (advanced): 58145.99ms
Improvement (Optimized vs Original): -1.84%
Improvement (Ultra-Optimized vs Original): 39.75%
```

**Comment by mikeburgh** [comment]
I just released version 1.11.7 give it a try and let me know how you go.

**Comment by ashouppe-pj** [comment]
@mikeburgh I loaded the latest version and was able to add the database as before, but still having issues once I go to use the database for anything. Here is the output I received after waiting right at 30 minutes to load (Note: This was using an Azure SQL connection type)

`2025-04-15 10:31:45.530 [info] Connection: shallow connection 'PJ_TEST' on 'PJ_TEST - Admin' (azure)
2025-04-15 10:31:45.544 [error] Connection: failed to find cached schema for 'PJ_TEST' on 'PJ_TEST - Admin' (shallow connection)
2025-04-15 10:32:02.300 [debug] MSSQL: executing query on 'PJ_TEST - Admin'
2025-04-15 10:32:02.448 [debug] MSSQL: processing query results on 'PJ_TEST - Admin', recordsets: 1
2025-04-15 10:32:02.449 [info] Connection: opened 'PJ_TEST' on 'PJ_TEST - Admin' (azure:SQL Azure - 12.0.2000.8)
2025-04-15 10:32:02.449 [debug] MSSQL: executing query on 'PJ_TEST - Admin'
2025-04-15 10:32:02.471 [debug] MSSQL: processing query results on 'PJ_TEST - Admin', recordsets: 1
2025-04-15 10:32:02.473 [debug] Connection: introspection of 'PJ_TEST' on 'PJ_TEST - Admin' starting
2025-04-15 10:32:02.473 [debug] MSSQL: executing query on 'PJ_TEST - Admin'
`

**Comment by mikeburgh** [comment]
Looks like you might be hitting a similar performance issue as in #440 with disk reads, I will update this issue when there is an new version to test with logging around the disk access to see if that's the cause..

**Comment by mikeburgh** [comment]
Can you give 1.11.9 a try, and share the output log once you enable debugging ?

**Comment by ashouppe-pj** [comment]
@mikeburgh Here ya go! This was all it gave me after waiting right at 25 minutes - and then I had to move on to other db operations. 

```2025-04-24 10:39:49.370 [info] Connection: opened 'PJ_TEST' on 'PJ_TEST-Admin' (azure:SQL Azure - 12.0.2000.8)
2025-04-24 10:39:49.371 [debug] MSSQL: executing query on 'PJ_TEST-Admin'
2025-04-24 10:39:49.399 [debug] MSSQL: processing query results on 'PJ_TEST-Admin', recordsets: 1
2025-04-24 10:39:49.400 [debug] FileStore: failed to find file 'schemas/ZhM1d6dsfhpZRRYw1ZkOc/PJ_TEST.data'
2025-04-24 10:39:49.401 [debug] Connection: introspection of 'PJ_TEST' on 'PJ_TEST-Admin' starting
2025-04-24 10:39:49.401 [debug] MSSQL: executing query on 'PJ_TEST-Admin'```

**Comment by ashouppe-pj** [comment]
@mikeburgh  looks like it finally ended with an error: 

```2025-04-24 11:50:28.493 [error] MSSQL: Error executing query on 'PJ_TEST-Admin', error: 'Connection lost - read ETIMEDOUT'
2025-04-24 11:50:28.495 [error] Connection: introspection of 'PJ_TEST' on 'PJ_TEST-Admin' error: Connection lost - read ETIMEDOUT

**Comment by ashouppe-pj** [comment]
@mikeburgh just wanted to reach out to see if there was anything further I could do/anything else I could provide to try and get past this issue?

**Comment by mikeburgh** [comment]
@ashouppe-pj Still thinking around solutions for this one.... Timeout indicates the server took too long getting the data, but that does not match up with those tests you did before.. they were all sub a few seconds (in terms of getting the data).

**Comment by mikeburgh** [comment]
This should be fixed now, closing it.
