### ISSUE TITLE
Row Count Mismatch in Postgres Tables

### ISSUE THREAD

**Issue by ChandraSaiKarthik** [dbcodeio/public#791]
**Summary**
The public.suppliers table actually holds 29 rows, but the table count is shown as 1 rows in the object tree.
This is observed in Postgres Database Tables Only. (MSSQL shows correctly with the same schema and data)

Postgres Database
<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/fdbf53b1-6a01-4976-9845-c8d16de0ad16" />

MSSQL Database
<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/67d9dc98-4b81-4f22-89fb-fca249ab5907" />

**Comment by mikeburgh** [comment]
On Postgres you need to run analyze or vacuum periodically to get more updated row count information

**Comment by ChandraSaiKarthik** [comment]
Perfect, it worked. (but i cant run the **vacuum** or **analyse** evevrytime)
<img width="1197" height="558" alt="Image" src="https://github.com/user-attachments/assets/701d1dd2-eb6a-4785-898b-91e47fcf3138" />


### There is another method to rely on for table counts:
<img width="1202" height="553" alt="Image" src="https://github.com/user-attachments/assets/97a8f9d5-d5bc-46ec-be9f-d6ac3b39b366" />

**Comment by mikeburgh** [comment]
Thanks, did not know that column was there… I have added support for it if it exists and fallback to the old rowtuples when it does not exist (it's not in some of the pg compatible engines like clickhouse, redshift).

Fixed in 1.17.27

**Comment by ChandraSaiKarthik** [comment]
<img width="525" height="769" alt="Image" src="https://github.com/user-attachments/assets/690d9e7a-eda8-4523-8ea6-d9ad9ec28769" />

I still see some issue in loading row counts in postgres only.

**Comment by mikeburgh** [comment]
what shows in select n_live_tup from pg_stat_all_tables for those tables ?

**Comment by ChandraSaiKarthik** [comment]
It shows the row count. I posted image in 1st image

**Comment by mikeburgh** [comment]
That's user_tables, I am using all_tables.

**Comment by ChandraSaiKarthik** [comment]
what do you mean by that.? can u pls elaborate.?

**Comment by mikeburgh** [comment]
I am using this query (or at least the pg_stat_all_tables) to get the counts.. not user_tables.. so hence, what does tihs query show for the tables in question: <br><br>select n_live_tup from pg_stat_all_tables <br><br>Although it really should not matter as these are just filtered views of the same information.. and much like vaccum these tables depend on configuration information with regards to if they will be updated/how accurate they are: [https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-STATS-SETUP](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-STATS-SETUP)

**Comment by ChandraSaiKarthik** [comment]
Yeah... Got You.... i overlooked it.
there is no proper way to get the exact row count without **vacuum**

**Comment by mikeburgh** [comment]
I have rolled this back to what it used before, but also filtered out -1 so if that's the value (no vacumm) it wont show.<br><br>Released in 1.17.35
