### ISSUE TITLE
User settings workbench.colorCustomizations are copied to workspace settings

### ISSUE THREAD

**Issue by arttu-karpinlehto** [dbcodeio/public#836]
All `workbench.colorCustomizations` settings from user `settings.json` are copied to `code-workspace` file whenever DBCode extension is used. In my particular case, the `code-workspace` file is part of git repo and every time DBCode is used, source control shows `code-workspace` as modified.

## Repro steps
1. Have `workbench.colorCustomizations` in user `settings.json`
2. Use DBCode extension.
3. See `workbench.colorCustomizations` copied to workspace file.

## Expected Behavior
Using DBCode should not modify code-workspace file.

## Actual Behavior
Code-workspace file is modified.

## Environment
- DBCode version: 1.17.34
- VS Code (or fork) version: 1.106.0
- OS: Windows 11 (WSL)
- Database: MariaDB
- Connection: direct

**Comment by mikeburgh** [comment]
Thanks, should be fixed now in 1.18.0

**Comment by arttu-karpinlehto** [comment]
Thanks for fast response! 

Unfortunately, colorCustomizations still appears in workspace file, but it's now empty:
```
"workbench.colorCustomizations": {}
```

This is version 1.18.0.

**Comment by mikeburgh** [comment]
Sorry, fixed one issue caused another. Fixed now on 1.19.5
