### ISSUE TITLE
mysql introspection error

### ISSUE THREAD

**Issue by wthee00** [dbcodeio/public#86]
Error:
this[(_0x192273(...)   _0x192273(...)   "ON")] is not a function

---
VSCode Version: 1.95.0
Extension Version: 1.3.15
OS: win32
Arch: x64
Database Version: mariadb.org binary distribution - 10.4.27-MariaDB

**Comment by mikeburgh** [comment]
I think I have tracked this down.. Can you confirm did you set the database type as MySQL or Maria ?

**Comment by wthee00** [comment]
> I think I have tracked this down.. Can you confirm did you set the database type as MySQL or Maria ?

Yes. I have set the database type to MySQL. 
![Image](https://github.com/user-attachments/assets/a02f4b97-fc4f-4acf-a668-4befc2cd0730)
this is my .env database configuration.
![Image](https://github.com/user-attachments/assets/4a7e64e3-e4d5-49d2-8f7e-b96a19677875)

**Comment by mikeburgh** [comment]
Thanks, I am working on a fix but if you changed the type to Maria in the connection form it will work as the underlying database is actually Maria

**Comment by mikeburgh** [comment]
Fixed in version 1.3.18

**Comment by wthee00** [comment]
The issue persists in some databases but not all, potentially due to a large number of tables?




Error:
_0x25aede[_0x27a9ac(...)]%3F.[_0x27a9ac(...)] is not a function

---
VSCode Version: 1.95.1
Extension Version: 1.3.18
OS: win32
Arch: x64
Database Version: mariadb.org binary distribution - 10.4.27-MariaDB

**Comment by wthee00** [comment]
When I use SQL query to query the database, the table is shown. But the table is not show in  the dropdown list.
![Image](https://github.com/user-attachments/assets/8748cdce-bb04-49c4-90a0-d81587ec7a93)

**Comment by mikeburgh** [comment]
It looks like you still have the connection set as MySQL.. If you update to the latest version of the extension it should correct it, otherwise edit the connection and change the type to MariaDB, that's the actual database you are running, and while it's MySQL compatible, there are some differences, and that's what is causing this issue.<br><br>If that does not solve it, let me know and if you can share the exact error (Screen shot is great) I can dig further.

**Comment by wthee00** [comment]
I changed the connection back to MySQL after updated to latest version which is 1.3.18. Before update, I change the connection to MariaDB also have error. Even now I change the connection to MariaDB also the same. 
![Image](https://github.com/user-attachments/assets/6b0f77c8-2648-4ae3-8434-c364ee65ea0d)
Error:
_0x25aede[_0x27a9ac(...)]%3F.[_0x27a9ac(...)] is not a function

**Comment by mikeburgh** [comment]
I just pushed a new version, can you give it a try ? I don't think it will be fixed, but it should provide me more information to hopefully track down where the issue is.<br><br>I tried replicating it with a MariaDB, same version and all the features (keys, indexes, trigers, functions etc) and was not able to replicate it.

**Comment by mikeburgh** [comment]
Closing this, you can re open it if it's still happening
