### ISSUE TITLE
mongodb introspection error

### ISSUE THREAD

**Issue by nrjais** [dbcodeio/public#863]
DBCode seems to be inpecting collection using commands which require extra permissions, can this be optional and fallback to something else so that basic db queries works, currently after this failure basic queries also don't work
the creds only have read permission on one db 

Error:
not authorized on db to execute command { collStats: "system.profile", lsid: { id: UUID("7edf1aab-c8a0-4ec0-8100-4d969d15e037") }, $clusterTime: { clusterTime: Timestamp(1764572519, 338)}, $readPreference: { mode: "primaryPreferred" }, $db: "db" }

---
VSCode Version: 1.105.1
Extension Version: 1.19.8
OS: darwin
Arch: arm64
Database Version: 4.0.28 - 4.0.28

**Comment by mikeburgh** [comment]
Should be fixed in 1.19.9

**Comment by nrjais** [comment]
Now failing with 
```
Error:
not authorized on pricingProd to execute command { aggregate: "system.profile", pipeline: [ { $project: { arrayofkeyvalue: { $objectToArray: "$$ROOT" } } }, { $limit: 10 }, { $unwind: "$arrayofkeyvalue" }, { $group: { _id: null, allkeys: { $addToSet: { name: "$arrayofkeyvalue.k", dataType: { $type: "$arrayofkeyvalue.v" } } } } }, { $unwind: "$allkeys" }, { $replaceRoot: { newRoot: "$allkeys" } } ], cursor: {}, lsid: { id: UUID("3f8e64cb-d96f-4cff-8f2f-5b3e0dfdf983") }, $clusterTime: { clusterTime: Timestamp(1764914466, 647), signature: { hash: BinData(0, 010119CA9CE28922859D2C8296D6A3116FED459), keyId: 752886299024267752 } }, $readPreference: { mode: "primaryPreferred" }, $db: "prod" }
```
version : 1.19.9

**Comment by mikeburgh** [comment]
Thanks, fixed in 1.19.10.. if you run into more, can you share more about how this user has been setup ? so I can replicate on my end and track them all down in one go.

**Comment by nrjais** [comment]
this are the permissions of the user
```
{
            "resource" : {
                "db" : "main",
                "collection" : ""
            },
            "actions" : [ 
                "createCollection", 
                "insert", 
                "remove", 
                "update"
            ]
        }
```

still have this issue with this user

also has `read` role

**Comment by mikeburgh** [comment]
Thanks, replicated it, give 1.22.4 a try

**Comment by MHunain-Official** [comment]
@mikeburgh  their is a same issue with the connection

**Comment by mikeburgh** [comment]
What error do you get ?

**Comment by mikeburgh** [comment]
Closing this, re open if you can share the error, or still having issues.
